- url: https://voicerepublic.com/users/re-publica-15
  img: images/sponsored_publishers/republica.png
  name: re:publica 2014/2015
  text: >-
    Europe’s biggest internet and digital conference can be listened
    to on Voice Republic since 2014.

- url: https://voicerepublic.com/users/frankfurter-buchmesse
  img: images/sponsored_publishers/frankfurt.png
  name: Frankfurt Book Fair
  text: >-
    The world’s most important event in the book business publishes
    selected content on Voice Republic.

- url: https://voicerepublic.com/users/hkw-berlin
  img: images/sponsored_publishers/kulturen.png
  name: Haus der Kulturen der Welt
  text: >-
    The international cultural center makes their project “100 Years
    of Now” audible on Voice Republic.

- url: https://voicerepublic.com/users/zentrum-geschichte-des-wissens-eth-universitat-zurich
  img: images/sponsored_publishers/zgw.svg
  name: ETH/University of Zurich
  text: >-
    The Center “History of Knowledge” regularly streams its events
    live from the Cabaret Voltaire. The colloquia and symposia can
    also be listened to in the archive.

- url: https://voicerepublic.com/users/Morgenstadt
  img: images/sponsored_publishers/frauenhofer.png
  name: Fraunhofer Institute
  text: >-
    Voice Republic accompanies the “Urban Future Conference 2015” and
    gives everyone who is interested the opportunity to listen to the
    talks.

- url: https://voicerepublic.com/users/maxim-gorki-theater
  img: images/sponsored_publishers/gorki.png
  name: Maxim Gorki Theater
  text: >-
    The Maxim Gorki Theater in Berlin is one of the most important
    theaters in the German-speaking area and publishes selected
    discussions, lectures and symposia on Voice Republic.

- url: https://voicerepublic.com/users/mosselectures
  img: images/sponsored_publishers/mosse.png
  name: Mosse Lectures at Humboldt University
  text: >-
    The lecture series “Mosse Lectures” at the Humboldt University in
    Berlin imparts knowledge on topics like history, politics,
    economy, arts and literature. The lectures can be listened to on
    Voice Republic.

- url: https://voicerepublic.com/users/leipziger-buchmesse
  img: images/sponsored_publishers/leipziger.jpg
  name: Leipziger Buchmesse
  text: >-
    Every Spring, the literature and media business meets up in 
    Leipzig and thousands of book fans hear their favourite authors 
    read.