# this file contains default content for sections (formatted in markdown)
en:
  root:
    index:
      title: '# Home to the spoken word'
  devise:
    mailer:
      confirmation_instructions:
        text: >-
          Thank you for signing up with us! To get started, you only
          need to confirm your email address by clicking here:


          %{link}


          Here we go:


          With your personal account you can now download all talks in
          the Voice Republic archive as podcasts and listen to them
          wherever and whenever you want to. You can also take part in
          the discussions during live talks.


          Of course, you can also start your own live stream or easily
          upload your audio files. Before a live talk, we recommend
          you conduct a test talk. You will find useful tips on how to
          use Voice Republic in our help section. If you have any
          further questions, please contact us directly under
          service@voicerepublic.com.
  pages:
    outdated_browser:
      text: >-
        ### You are using an outdated browser.

        (You are using an old version of %{browser} which is
        %{version}.)


        Unfortunately, at this stage, we do not have the manpower to
        support every browser. We rather strive to to build the most
        awesome user experience using modern browsers. For a good
        experience with Voice Republic, please upgrade to the newest
        version or download one of the browsers below:


        * [Download Chrome 33+](https://www.google.com/intl/en/chrome/browser/)

        * [Download Firefox 28+](http://www.mozilla.org/en-US/firefox/new/)

        * **Safari 7** (If you are on OSX < 10.9, you need to upgrade to
          get a newer version of Safari. It is easier to use Chrome or
          Firefox.)

        * [Download Internet Explorer](http://windows.microsoft.com/en-us/internet-explorer/download-ie)
          (If you have an older version of Windows, you need to upgrade to get a newer version of Internet explorer. It's easier to use Chrome or Firefox.)
    publish:
      head_1: "# Publish your own content online"
      text_1: >-

        At Voice Republic, your content is in good company. Our archive is growing
        daily with high-class lectures, discussions
        and readings from the fields of culture, sciences, politics
        and business. Expand your reach beyond the venue walls to interested listeners around the world.
        Thanks to our browser-based technology, you'll need no extra gear. 
        [Starting at 12€ per Talk](/pricing)
        your own audio channel is only a few clicks away...

      head_2: "## The Voice Republic live stream"
      text_2: >-

        Are you orgranizing a conference, discussion panel, or
        holding lectures and workshops yourself? With Voice Republic
        you can publish your content to the whole world and reach a
        large audience.


        Broadcasting your own live stream is easy with Voice Republic's
        browser-based technology. You configure a talk
        in your Voice Republic account and simply click
        "Start" and "Stop" during the event. The technology you need on site is only
        a computer with internet access and an audio source. The
        comment feature gives you the opportunity to interact with
        your online audience. Listeners can comment and ask questions
        in real time. 


        After your event, your audio content is
        in good hands with us. All Talks are stored on the Voice
        Republic servers and are searchable in the archive immediately
        after the live broadcast.



      head_3: "## The Voice Republic audio upload"
      text_3: >-

        Already have existing
        recordings? You can also use our audio archive. Just upload
        your audio files and add your own photos, descriptive texts
        and—if you want to—presentation slides. Everyone can now
        listen to your content online or download it as a podcast. You
        can easily embed the Voice Republic Player into your own web
        page and share the Talks on social networks.