# this file reflects standard settings for development
# overrides for production can be found in
# `config/settings/production.yml`
durations: [ 30, 45, 60, 90, 120, 240 ]
priority_timezones: Berlin|Bern
audio:
  process_chain: precursor normalize_fragments kluuu_merge trim cut normalize compress jinglize m4a mp3 ogg copy_clean cleanup
  override_chain: m4a mp3 ogg copy_clean cleanup
rtmp:
  # all paths get expanded with `Rails.root`
  # which doesn't affect absolute paths
  build_path:       local/rtmp
  archive_path:     local/archive
  archive_raw_path: local/archive_raw
  recordings_path:  local/recordings
  #offrecord: "rtmp://172.21.21.171/offrecord"
  #record: "rtmp://172.21.21.171/record"
  #offrecord: "rtmp://localhost/offrecord"
  #record: "rtmp://localhost/record"
  offrecord: "rtmp://localhost/offrecord"
  record: "rtmp://localhost/record"
  log_notifications: true
  #######################################
  # entries used by config/rtmp.conf.erb
  #######################################
  send_notifications: true
  # callback_base must be an absolute url and is used for
  # notifications `/notify` and authentication `/auth`
  callback_base: 'http://0.0.0.0:3000/rtmp'
  record_max_size: 100M
  #record_interval: 5m
  record_interval: false
  authenticate: true
  worker_processes: 1

# This is a dummy entry for CircleCI. The actual values have to be
# stored in `config/settings.local.yml`, since RtmpWatcher and Faye
# read the value directly from there.
faye:
  server: http://localhost:9292/faye
  secret_token: supersecret

errbit:
  enabled: false
  api_key: 'this will be set on the stages in app/shared/config/settings.local.yml'
devise:
  from_address: "Voice Republic <service@voicerepublic.com>"
  secret_key: '077e0e804b07d4284d6960b23579ca07b7a83bdf65f5c1a21d8d256e3d0ddfaec82bc294bf91e44bb0cc604757141f6b175d7290469fb881e4d347082f7e6481'
rspec:
  gc_cycle: 20
# This list needs to be updated constantly
supported_browsers:
  chrome: 30
  safari: 7
  ie: 10
  firefox: 24
mail_domain: 'localhost'
flyer:
  location: /system/flyer
  path: public/system/flyer
# S3 upload bucket for talks. For S3 uploads we are using CORS.
# Therefore, we have three S3 buckets - each for a specific FQDN:
#
# * localhost:3000             -> vr-audio-uploads-dev
# * staging.voicerepublic.com  -> vr-audio-uploads-staging
# * voicerepublic.com          -> vr-audio-uploads-live
storage:
  media: vr-dev-media
  import: vr-dev-import
  uploads: vr-audio-uploads-dev
paths:
  log: local/log
  jingles:
    in: public/audio/Jingle_05.wav
    out: public/audio/Jingle_05.wav
root_url: 'http://localhost:3000'
blackbox:
  # http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00001260.html
  silence_level: 0
  silence_timeout: 2000
limit:
  text: 2300
  string: 140
slack:
  token: VtybT1KujQ6EKstsIEjfZ4AX
  icon:
    default: ':no_entry_sign:'
    audio:   ':headphones:'
    email:   ':e-mail:'
    trigger: ':hand:'
    ci:      ':package:'
googleanalytics:
  token: UA-46754662-1
default_venue_defaults:
  en:
    title: My Talks
    teaser: Various talks
    description: |
      Various talks, that don't belong to any particular series
    tag_list: default
venue_default_attributes:
  en:
    teaser: Add your teaser here.
    description: Add your description here.
    tag_list: untagged
welcome_credits: 2

# this needs to be overridden by `app/shared/config/settings.local.yml`
activemerchant:
  billing_mode: test
  gateway: paypal_express
# sandbox account
paypal:
  login: billing-facilitator_api1.voicerepublic.com
  password: DN49HF4NJFV2VXCY
  signature: A.s24tjnJ2mWWFD4MAbxh6.qj5MbA1fFTAbSjKBXjRPo5omKdKMEMQgY
developers:
  - phil@voicerepublic.com
  - munen@voicerepublic.com
  - nick@voicerepublic.com
  - munen@dispatched.ch
  - accounts@dispatched.ch
  - spam@dispatched.ch
payment_enabled: true
