target: local

# this file reflects standard settings for development
# overrides for production can be found in
# `config/settings/production.yml`
durations: [ 30, 45, 60, 90, 120, 240 ]
priority_timezones: Berlin|Bern
audio:
  override_chain: jinglize m4a mp3 ogg cleanup
  archive_chain: select wavify merge trim desilence normalize jinglize m4a mp3 ogg cleanup
rtmp:
  # all paths get expanded with `Rails.root`
  # which doesn't affect absolute paths
  build_path:       local/rtmp
  archive_path:     local/archive
  archive_raw_path: local/archive_raw
  recordings_path:  local/recordings
  #offrecord: "rtmp://172.21.21.171/offrecord"
  #record: "rtmp://172.21.21.171/record"
  #offrecord: "rtmp://localhost/offrecord"
  #record: "rtmp://localhost/record"
  offrecord: "rtmp://localhost/offrecord"
  record: "rtmp://localhost/record"
  log_notifications: true
  #######################################
  # entries used by config/rtmp.conf.erb
  #######################################
  send_notifications: true
  # callback_base must be an absolute url and is used for
  # notifications `/notify` and authentication `/auth`
  callback_base: 'http://0.0.0.0:3000/rtmp'
  record_max_size: 100M
  #record_interval: 5m
  record_interval: false
  authenticate: true
  worker_processes: 1

# This is a dummy entry for CircleCI. The actual values have to be
# stored in `config/settings.local.yml`, since RtmpWatcher and Faye
# read the value directly from there.
faye:
  server: http://localhost:9292/faye
  #server: http://192.168.178.21:9292/faye
  secret_token: supersecret

default_pins:
  - willkommen-bei-voice-republic

errbit:
  enabled: false
  api_key: 'this will be set on the stages in app/shared/config/settings.local.yml'
  environment: 'development'
devise:
  from_address: "Voice Republic <service@voicerepublic.com>"
  secret_key: '077e0e804b07d4284d6960b23579ca07b7a83bdf65f5c1a21d8d256e3d0ddfaec82bc294bf91e44bb0cc604757141f6b175d7290469fb881e4d347082f7e6481'
# This list needs to be updated constantly
supported_browsers:
  chrome: 30
  safari: 7
  ie: 10
  firefox: 24
mail_domain: 'localhost'
flyer:
  location: /system/flyer
  path: public/system/flyer
# S3 upload bucket for talks. For S3 uploads we are using CORS.
# Therefore, we have three S3 buckets - each for a specific FQDN:
#
# * localhost:3000             -> vr-audio-uploads-dev
# * staging.voicerepublic.com  -> vr-audio-uploads-staging
# * voicerepublic.com          -> vr-audio-uploads-live
storage:
  media:             vr-dev-media@us-east-1
  import:            vr-dev-import@us-east-1
  upload_audio:      vr-audio-uploads-dev@us-east-1
  upload_slides:     vr-slide-uploads-dev@us-east-1
  backup_recordings: vr-euc1-dev-backup-recordings@eu-central-1
paths:
  log: local/log
  jingles:
    in: https://voicerepublic.com/audio/jingle_08.wav
    out: https://voicerepublic.com/audio/jingle_08.wav
root_url: 'http://localhost:3000'
blackbox:
  # http://help.adobe.com/en_US/AS2LCR/Flash_10.0/help.html?content=00001260.html
  silence_level: 0
  silence_timeout: 2000
limit:
  text: 2300
  string: 140
  varchar: 255
simon:
  enabled: false
slack:
  token: VtybT1KujQ6EKstsIEjfZ4AX
  icon:
    default: ':no_entry_sign:'
    audio:   ':headphones:'
    email:   ':e-mail:'
    trigger: ':hand:'
    ci:      ':package:'
  # these are only used in production and need to be changed for live
  system_channel: '#vr_sys_staging'
  revenue_channel: '#vr_sys_staging'
  # TODO remove slack.tag from local settings on staging and live
googleanalytics:
  token: UA-46754662-1

default_series_defaults:
  en:
    title: My Talks
    teaser: Various talks
    description: |
      Various talks, that don't belong to any particular series
    tag_list: default
default_venue_defaults:
  en:
    name: 'Venue of %{user}'
series_default_attributes:
  en:
    teaser: Add your teaser here.
    description: Add your description here.
    tag_list: untagged

welcome_credits: 2

# this needs to be overridden by `app/shared/config/settings.local.yml`
activemerchant:
  billing_mode: test
  gateway: paypal_express
# sandbox account
paypal:
  login: billing-facilitator_api1.voicerepublic.com
  password: DN49HF4NJFV2VXCY
  signature: A.s24tjnJ2mWWFD4MAbxh6.qj5MbA1fFTAbSjKBXjRPo5omKdKMEMQgY
developers:
  - phil@voicerepublic.com
  - munen@voicerepublic.com
  - nick@voicerepublic.com
  - munen@dispatched.ch
  - accounts@dispatched.ch
  - spam@dispatched.ch
sitemap: http://localhost:3000/root/index.xml

icecast:
  ec2:
    #image: ami-421cf82d (icebox)
    #image: ami-5a806335 (icebox protoype)
    #image: ami-b39173dc (icebox v3 - defunct)
    #image: ami-30f2105f (icebox 3.1)
    #image: ami-d422cebb (icebox 3.2 - bad)
    #image: ami-d822ceb7 (icebox 3.3)
    #image: ami-b31cf3dc (icebox 3.4 - renamed endpoints)
    #image: ami-b81cf3d7 (icebox 3.5 - update icecast to 2.4.2 + cors, DEFUNCT)
    #image: ami-f21bf49d (icebox 3.6 - fixed ready)
    #image: ami-63814d0c (icebox 3.7 - https, curl retry, upgr., docker1.12, DEFUNKT)
    #image: ami-a2804ccd (icebox 3.8 - cleanup DEFUNKT)
    #image: ami-c1814dae (icebox 3.9 - DEFUNKT)
    #image: ami-31834f5e (icebox 3.10 - DEFUNKT)
    #image: ami-659d510a (icebox 3.11)
    #image: ami-bf24e8d0 (icebox 3.12 better cors, cors defunkt)
    #image: ami-9826eaf7 (icebox 3.13 fixed cors)
    #image: ami-13e3367c (icebox 3.14 transcoding defunkt + updgrade)
    #image: ami-26e63349 (icebox 3.15 transcoding + ffmpeg)
    #image: ami-e5e1348a (icebox 3.16 fixed port)
    #image: ami-7a0fda15 (icebox 3.17 log transcoding to s3)
    #image: ami-2d0dd842 (icebox 3.18 fixed typo for aac)
    #image: ami-fbc21694 (icebox 3.19 consistent uid/gid)
    #image: ami-ecd60583 (icebox 3.20 liquidsoap)
    #image: ami-bf4d9ed0 (icebox 3.21 improved live transcoding)
    #image: ami-b5ca6fda (icebox 3.22 fix transc. stereo signals + pull icebox.liq)
    image: ami-b5ca6fda
    default_instance_type: t2.micro
    security_group: Icecast Servers
    key_name: phil-ffm
  url:
    protocol: http
    port: 80
  callback_url: http://change.in.your.local.settings.file/icebox

  # TODO remove
  # this needs to be overridden by `app/shared/config/settings.local.yml`
  host: localhost
  port: 8080

fog:
  compute:
    provider: AWS
    aws_access_key_id: needs to be set
    aws_secret_access_key: needs to be set
    region: eu-central-1
  storage:
    provider: AWS
    aws_access_key_id: AKIAIGKSA6ESEFZV4DQA
    aws_secret_access_key: 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

devices:
  endpoint:
    live: https://voicerepublic.com/api/devices
    staging: https://staging:oph5lohb@staging.voicerepublic.com/api/devices
    # actually you need to set this in your local file
    dev: http://needs.to.be.set.locally/api/devices
  faye:
    server: http://needs.to.be.set.locally/
    secret_token: supersecret
  storage:
    bucket: vr-euc1-dev-backup-recordings@eu-central-1
    # user: device
    aws_access_key_id: AKIAI7HSKHN3FBT2KAZQ
    aws_secret_access_key: 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
