rtmp:
  build_path:         /home/app/app/shared/rtmp
  archive_path:       /home/app/app/shared/archive
  archive_raw_path:   /home/app/app/shared/archive_raw
  recordings_path:    /home/app/app/shared/recordings
  worker_processes:   1
  offrecord:          'rtmp://voicerepublic-staging.sky.ungleich.ch/offrecord'
  record:             'rtmp://voicerepublic-staging.sky.ungleich.ch/record'
  log_notifications:  false
  send_notifications: true
  callback_base:      'http://localhost/rtmp'
  record_max_size:    '100M'
  authenticate:       true
paths:
  log: /home/app/app/shared/process_log
errbit:
  enabled: true
simon:
  enabled: true